
name: Run junit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  intergration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup test environment
      run: ./test_environment/setup_fakezod.sh
    - name: Test with Gradle
      run: ./gradlew test --stacktrace # --info
      # not strictly necessary because the ci instance is spun down anyways but i guess its handy if it does something in the future
    - name: Teardown test environment
      run: ./test_environment/teardown_fakezod.sh

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: build/reports/tests/test/*
        retention-days: 30


