
name: Run junit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  intergration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup test environment
      run: ./scripts/setup_fakezod.sh
    - name: Test with Gradle
      run: ./gradlew test --stacktrace # --info
      # not strictly necessary because the ci instance is spun down anyways but i guess its handy if it does something in the future
    - name: Teardown test environment
      run: ./scripts/teardown_fakezod.sh
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
# ok so that actually worked but I'm gonna try smtn else
#    - name: Publish Unit Test Results
#       uses: EnricoMi/publish-unit-test-result-action@v1.6
#       if: always()
#       with:
#         working-directory: ${{ github.workspace }}
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         # todo figure out the correct relative path
#         files: build/test-results/**/*.xml
