
name: Run junit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ${{ github.worspace }}

jobs:
  intergration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup test environment
      run: ./setup_fakezod.sh
    - name: Test with Gradle
      run: ./gradlew test --info --stacktrace
    - name: List working directory
      run: pwd
      run: ls -la
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # todo figure out the correct relative path
        files: build/test-results/**/*.xml
